export const COMPANIES_TO_DISCOVER: string[] = [
  "3M India", "3i Infotech", "360 Degree Cloud Technologies", "Accenture",
  "Accuster Technologies", "Addend / Adventure India Journey", "AECOM", "Affle",
  "Agro Tech Foods (ATFL)", "Air India", "AkzoNobel", "Alten", "Alvaria",
  "Amantya Technologies", "American Express", "American Express Global Business Travel",
  "Amway", "Anaqua", "Aptara", "Arcadis", "Assurant Automotive Warranty Solutions",
  "Avery Dennison", "Avnet", "Axa Xl", "Azilen", "Baker Tilly", "Baker Tilly Dhc",
  "Barco", "BASF", "Bct Consulting", "Beacon / Baxter", "Beckman Coulter",
  "Bentley Systems", "Beri Udyog", "Bill Gosling", "Binary Semantics", "Bitla Software",
  "Blue Rose Publishers", "Blue Star", "BDO Rise", "Bold Technology Systems",
  "Bottle Lab Technologies", "Bounteous", "Brainlabs", "Bravura Solutions", "Bry Air",
  "Bunge", "Buro Happold", "BUSINESSNEXT",
  "C1 India", "Cargill", "Carrier", "Celerant / Chegg", "Cerillion Technologies",
  "Chetu", "Chai Point", "Cloudstrats Technologies", "Coforge", "Cognizant",
  "Colt Technology Services", "Corbus", "Copeland", "Corning Technologies", "Credera",
  "Crowe", "Cynoteck Technology Solutions", "Dachser", "Data Intensity", "Dayforce",
  "DCM Shriram", "Ddreg Pharma", "Dentsu Aegis Network", "Designtech Systems", "Dtcc",
  "DURR",
  "Ecifm Solutions", "Egon Zehnder", "Envecon It Systems", "Envision", "Epam Systems",
  "Eptura", "Espire Infolabs", "ETS India", "Everest Business Advisory India", "Evora",
  "Excelra", "Excelsoft Technologies", "Exigent", "Expedia", "ExxonMobil",
  "Extramarks Education", "Fareportal", "FedEx", "Fidelity International", "FIS",
  "FNZ Group", "Foundever", "Fractal Analytics", "Fusion CX", "Gallagher",
  "Giesecke & Devrient", "Glenmark Pharmaceuticals", "GreyOrange", "Hawkscode",
  "Helmsman India Quality Technology Services", "Highlands Info Tech", "Hilton Hotels",
  "Hindustan Syringes & Medical Devices (HMD)", "Hitachi", "Hitachi Digital",
  "HL Mando Softtech", "Horiba India", "Hsbc", "HTC Global Services",
  "Icreon Communications", "ICICI Lombard", "IDOM", "IndiaMART", "Indegene", "In2IT",
  "Informa", "Insight Alpha", "Innovecture", "Inovalon India", "Integra Global Solutions",
  "Integral Ad Science", "Interra Systems", "Intertek", "Intex Technologies",
  "Investors Clinic", "IP E Global", "IQor", "IQVIA", "Jamna Auto Industries",
  "Jindal Stainless (JSL)", "Jubilant Pharmova", "Justdial", "Kansai Nerolac",
  "Keyboards Studios", "Kia India", "Koshda Buildcon", "Kotak Mahindra Bank",
  "Kpmg Apac", "Kritikal Solutions", "Kroll", "Kyndryl", "Launch It Consulting",
  "LatentView", "Leighton Asia", "Lingual Consultancy Services (LC)", "Lixil",
  "Lloyd Insulations", "Logic Planet", "Lorven Technologies", "LTM", "Lumen Technologies",
  "Lumina Datamatics", "Macadam Beekay / Macawber Beekay", "Macquarie",
  "Magic EdTech", "Majid Al Futtaim", "Marsh McLennan", "Mastercard", "Mcafee",
  "McCormick India", "McDermott", "Metlife", "Meril", "Merino Services",
  "MetaDesign Solutions (MDS)", "Michael Page", "Milliman", "Mobiloitte Technologies",
  "Mondelez", "Moodys Analytics", "Morris Garages", "Mott Macdonald",
  "Movate Technologies", "Multisoft Systems", "Mynd", "MYK LATICRETE",
  "NCR Voyix", "Net2Source LLP", "Netcom Learning", "Netscribes", "NetTantra",
  "Neustar / Newgen", "NIIT", "NJ Group", "Novo Nordisk", "NTT DATA", "NTT DATA Inc.",
  "Nvidia", "Oppo", "Oracle", "Orange Business Services", "Orion Secure",
  "Otis", "Pearce Services Global", "Peta India", "Pernod Ricard", "Plative",
  "Prescient Healthcare Group", "Protiviti India", "Quadlabs Technologies",
  "Quality Solutions", "Quantum Integrators", "Quess", "Raad Systems",
  "Rackspace Technology", "Ramboll", "Randstad", "Reach Technologies",
  "Relevance Lab", "Reliance Retail", "Rites", "RNF Technologies", "Rohde & Schwarz",
  "Rxlogix Corporation", "SAS Research and Development (SAS R&D)", "Saksoft",
  "Sandhar Technologies", "Sarla Advantech", "Scalable Systems",
  "Security and Intelligence Services (SIS)", "Securitas", "Secure Meters", "SE2",
  "Segula Technologies", "Sentiss Pharma", "Shapoorji Pallonji Group", "Shell Infotech",
  "Sirionlabs", "Sita", "Skillmine", "Smec", "Sodexo", "Softage Information Technology",
  "Sophos", "Sonata Software", "Sopra Steria", "Sourcefuse Technologies", "SPECTRAFORCE",
  "Steag Energy Services", "STL Digital", "Stellar Information Technology", "Straive",
  "StraViso", "Sun Pharma", "Suzuki Motorcycle", "Synapseindia", "Synechron", "Synopsys",
  "Taboola", "Talbros Automotive Components", "Tandems", "Tanisha Systems",
  "Tata Communications", "Tata Elxsi", "Tata Power", "Tata Technologies", "Tavant",
  "Tcg Digital Solutions", "Tech Mahindra", "TechSci Research",
  "Tecnics Integration Technologies", "TecQubes Technologies", "Tecumseh Products",
  "TENARAI TECHNOLOGIES PRIVATE LIMITED", "Tenneco", "Tex Corp", "The BIM Engineers",
  "Thiess", "Toppan Merrill", "Toyota Tsusho", "Tractebel", "Tredence",
  "Trinamix Systems", "Trivitron Healthcare", "TRIVENI ENGINEERING AND INDUSTRIES",
  "Trueblue", "TUV SUD South Asia", "UL Solutions", "Unitech", "Unitedlex", "Uniqlo",
  "V Group", "Vahdam Teas", "VEHERE TECHNOLOGIES PRIVATE LIMITED",
  "Venus Remedies (VRL)", "Vertiv Energy", "Vichara Technologies", "VISTRA",
  "Vizexperts", "Vlcc", "Vodafone Idea Limited",
  "VOLKSWAGEN GROUP DIGITAL SOLUTIONS PRIVATE LIMITED", "vivo", "Winjit Technologies",
  "WinWire", "Willis Towers Watson (WTW)", "World Resources Institute (WRI)", "Wework",
  "Xerox", "Yum! India", "Zensar", "ZTE Corporation", "ZS",
  "ZoomRx Healthcare Technology Solutions",
];